apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: myreactdockerrepo
        image: akstest12.azurecr.io/mim500/react-text-analysis:#{Build.BuildId}#
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-svc
spec:
  selector:
    app: my-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer